<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\UpdateAvatarRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use OpenAI\Laravel\Facades\OpenAI;

class AvatarController extends Controller
{
    // function that handles user uploading avatar from their computer
    public function update(UpdateAvatarRequest $request)
    {
        // authenticated user
        // $path = $request->file('avatar')->store('avatars', 'public');
        $path = Storage::disk('public')->put('avatars',$request->file('avatar'));
        // dd($path);

        // replace the old avatar with the new avatar
        if($oldAvatar = $request->user()->avatar){
            Storage::disk('public')->delete($oldAvatar);
        }

        auth()->user()->update(['avatar' => $path]);
        // dd(auth()->user());

        // svaed avatar
        // return response()->redirectTo('/profile');
        // return response()->redirectTo(route('profile.edit'));
        // return back()->with('message', 'Avatar has been changed');
        return redirect(route('profile.edit'))->with('message', 'Avatar is updated');
    }

    // function that generates tailored avatar for user
    public function generate(Request $request)
    {
        $result = OpenAI::images()->create([
            // 'model' => 'dall-e-2',
            'prompt' => "create a Japanese anime avatar for user based on their name ".auth()->user()->name,
            'n' => 1,
            'size' => '256x256',
        ]);
        // get the contents of the avatar generated by OpenAI
        $contents = file_get_contents($result->data[0]->url);
        // assign a random name to the avatar
        $filename = Str::random(25);

        // replace the old avatar with the new avatar
        if($oldAvatar = $request->user()->avatar){
            Storage::disk('public')->delete($oldAvatar);
        }

        Storage::disk('public')->put("avatars/$filename.jpg", $contents);
        // updates the user's record in the database
        auth()->user()->update(['avatar' => "avatars/$filename.jpg"]);
        return redirect(route('profile.edit'))->with('message', 'Avatar is updated');
        


    }

}
